import type { Product } from "./types"

export const products: Product[] = [
  {
    id: "1",
    name: "Picadillo de pollo MDM",
    description: "Picadillo de pollo MDM de alta calidad. Precio por libra.",
    price: 260,
    discount: 0,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/picadillo-0jPMsILlh4UyHBVwHfVbShwN5migTj.webp",
    category: "carnes",
    location: "Camagüey",
    publishDate: "2023-05-15",
    contactType: "whatsapp",
    contactNumber: "+58850138",
    sellerName: "tuMercao",
    sellerAvatar: "/placeholder.svg",
    sellerMemberSince: "2022",
  },
  {
    id: "2",
    name: "Detergente 500g",
    description: "Detergente en polvo de 500 gramos. Limpieza profunda y aroma duradero.",
    price: 450,
    discount: 0,
    image:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/detergente_500g-J4Fa5snn5rIAF5l4rfcUBFiHQhnk5C.webp",
    category: "limpieza",
    location: "Camagüey",
    publishDate: "2023-05-16",
    contactType: "whatsapp",
    contactNumber: "+58850138",
    sellerName: "tuMercao",
    sellerAvatar: "/placeholder.svg",
    sellerMemberSince: "2022",
  },
  {
    id: "3",
    name: "Detergente 1kg",
    description: "Detergente en polvo de 1 kilogramo. Rinde para más lavados con la misma calidad.",
    price: 850,
    discount: 0,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/detergente_1kg-hCYm4v4Gaa9kHX5QvFyIUYD6tKN0OT.webp",
    category: "limpieza",
    location: "Camagüey",
    publishDate: "2023-05-16",
    contactType: "whatsapp",
    contactNumber: "+58850138",
    sellerName: "tuMercao",
    sellerAvatar: "/placeholder.svg",
    sellerMemberSince: "2022",
  },
  {
    id: "4",
    name: "Fideos sabor Camarón con Pollo",
    description: "Fideos instantáneos con delicioso sabor a camarón y pollo. Preparación rápida.",
    price: 180,
    discount: 0,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/fideos_camaron-8F3BkiQAnxtKRz17oWbDoZJeNAwnmu.webp",
    category: "alimentos",
    location: "Camagüey",
    publishDate: "2023-05-17",
    contactType: "whatsapp",
    contactNumber: "+58850138",
    sellerName: "tuMercao",
    sellerAvatar: "/placeholder.svg",
    sellerMemberSince: "2022",
  },
  {
    id: "5",
    name: "Fideos sabor Res",
    description: "Fideos instantáneos con auténtico sabor a res. Listos en minutos.",
    price: 180,
    discount: 0,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/fideos_res-RocNHCg1yyf327TkcZQ4xr4OIBSbNl.webp",
    category: "alimentos",
    location: "Camagüey",
    publishDate: "2023-05-17",
    contactType: "whatsapp",
    contactNumber: "+58850138",
    sellerName: "tuMercao",
    sellerAvatar: "/placeholder.svg",
    sellerMemberSince: "2022",
  },
  {
    id: "6",
    name: "Fideos sabor Cerdo",
    description: "Fideos instantáneos con sabroso sabor a cerdo. Perfectos para una comida rápida.",
    price: 180,
    discount: 0,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/fideos_cerdo-R50gEbwjTsgSOm1BeyAajCiM8rJRQV.webp",
    category: "alimentos",
    location: "Camagüey",
    publishDate: "2023-05-17",
    contactType: "whatsapp",
    contactNumber: "+58850138",
    sellerName: "tuMercao",
    sellerAvatar: "/placeholder.svg",
    sellerMemberSince: "2022",
  },
  {
    id: "7",
    name: "Fideos sabor Pollo",
    description: "Fideos instantáneos con clásico sabor a pollo. El favorito de todos.",
    price: 180,
    discount: 0,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/fideos_pollo-bTsHJHzAKz42QhepPgHXe7ieM8IMcx.webp",
    category: "alimentos",
    location: "Camagüey",
    publishDate: "2023-05-17",
    contactType: "whatsapp",
    contactNumber: "+58850138",
    sellerName: "tuMercao",
    sellerAvatar: "/placeholder.svg",
    sellerMemberSince: "2022",
  },
  {
    id: "8",
    name: "Salchichas",
    description: "Salchichas de alta calidad. Ideales para desayunos, almuerzos o cenas rápidas.",
    price: 380,
    discount: 0,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/salchichas-fYtT1BlM9H6Vnj5P0c9LkMWxROBpe5.webp",
    category: "carnes",
    location: "Camagüey",
    publishDate: "2023-05-18",
    contactType: "whatsapp",
    contactNumber: "+58850138",
    sellerName: "tuMercao",
    sellerAvatar: "/placeholder.svg",
    sellerMemberSince: "2022",
  },
  {
    id: "9",
    name: "Huevo (unidad)",
    description: "Huevo fresco de calidad. Precio por unidad.",
    price: 110,
    discount: 0,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Huevo-oNCmykiQl4G7oftF5Iza6NQSHTrnuB.webp",
    category: "alimentos",
    location: "Camagüey",
    publishDate: "2023-05-19",
    contactType: "whatsapp",
    contactNumber: "+58850138",
    sellerName: "tuMercao",
    sellerAvatar: "/placeholder.svg",
    sellerMemberSince: "2022",
  },
  {
    id: "10",
    name: "Huevo (cartón)",
    description: "Cartón de huevos frescos. Contiene 30 unidades.",
    price: 3200,
    discount: 0,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Huevo-oNCmykiQl4G7oftF5Iza6NQSHTrnuB.webp",
    category: "alimentos",
    location: "Camagüey",
    publishDate: "2023-05-19",
    contactType: "whatsapp",
    contactNumber: "+58850138",
    sellerName: "tuMercao",
    sellerAvatar: "/placeholder.svg",
    sellerMemberSince: "2022",
  },
  {
    id: "11",
    name: "Croquetas",
    description: "Deliciosas croquetas listas para freír. Sabor tradicional.",
    price: 200,
    discount: 0,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/croquetas-zIW5y0qqdirnC5eIjy8VPB3ayX25KG.webp",
    category: "alimentos",
    location: "Camagüey",
    publishDate: "2023-05-20",
    contactType: "whatsapp",
    contactNumber: "+58850138",
    sellerName: "tuMercao",
    sellerAvatar: "/placeholder.svg",
    sellerMemberSince: "2022",
  },
]
