import type { Product } from "./types"

export const products: Product[] = [
  {
    id: "1",
    name: "Picadillo de pollo MDM",
    description: "Picadillo de pollo MDM de alta calidad. Precio por libra.",
    price: 260,
    discount: 0,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/picadillo-OXN3AQhwhHZecbnC9XweXKN4kQjVHr.webp",
    category: "carnes",
    location: "Camagüey",
    publishDate: "2023-05-15",
    contactType: "whatsapp",
    contactNumber: "+58850138",
    sellerName: "tuMercao",
    sellerAvatar: "/placeholder.svg",
    sellerMemberSince: "2022",
  },
  {
    id: "2",
    name: "Detergente 500g",
    description: "Detergente en polvo de 500 gramos. Limpieza profunda y aroma duradero.",
    price: 450,
    discount: 0,
    image:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/detergente_500g-9dLatG65Y52Urj5ysHcrDW3ZOm5ALg.webp",
    category: "limpieza",
    location: "Camagüey",
    publishDate: "2023-05-16",
    contactType: "whatsapp",
    contactNumber: "+58850138",
    sellerName: "tuMercao",
    sellerAvatar: "/placeholder.svg",
    sellerMemberSince: "2022",
  },
  {
    id: "3",
    name: "Detergente 1kg",
    description: "Detergente en polvo de 1 kilogramo. Rinde para más lavados con la misma calidad.",
    price: 850,
    discount: 0,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/detergente_1kg-yXgD5OfAg35j5hY5AmZJ7DcA3oyHYg.webp",
    category: "limpieza",
    location: "Camagüey",
    publishDate: "2023-05-16",
    contactType: "whatsapp",
    contactNumber: "+58850138",
    sellerName: "tuMercao",
    sellerAvatar: "/placeholder.svg",
    sellerMemberSince: "2022",
  },
  {
    id: "4",
    name: "Fideos sabor Camarón con Pollo",
    description: "Fideos instantáneos con delicioso sabor a camarón y pollo. Preparación rápida.",
    price: 180,
    discount: 0,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/fideos_camaron-RWNNEB8tm0au0GClR0YwaLI3yYIKW1.webp",
    category: "alimentos",
    location: "Camagüey",
    publishDate: "2023-05-17",
    contactType: "whatsapp",
    contactNumber: "+58850138",
    sellerName: "tuMercao",
    sellerAvatar: "/placeholder.svg",
    sellerMemberSince: "2022",
  },
  {
    id: "5",
    name: "Fideos sabor Res",
    description: "Fideos instantáneos con auténtico sabor a res. Listos en minutos.",
    price: 180,
    discount: 0,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/fideos_res-2Pw7YYVmlVLeQ1IHVY68QSUFQwacnk.webp",
    category: "alimentos",
    location: "Camagüey",
    publishDate: "2023-05-17",
    contactType: "whatsapp",
    contactNumber: "+58850138",
    sellerName: "tuMercao",
    sellerAvatar: "/placeholder.svg",
    sellerMemberSince: "2022",
  },
  {
    id: "6",
    name: "Fideos sabor Cerdo",
    description: "Fideos instantáneos con sabroso sabor a cerdo. Perfectos para una comida rápida.",
    price: 180,
    discount: 0,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/fideos_cerdo-HxS0I0dHULuK9B8kpduJqJlrKbtytg.webp",
    category: "alimentos",
    location: "Camagüey",
    publishDate: "2023-05-17",
    contactType: "whatsapp",
    contactNumber: "+58850138",
    sellerName: "tuMercao",
    sellerAvatar: "/placeholder.svg",
    sellerMemberSince: "2022",
  },
  {
    id: "7",
    name: "Fideos sabor Pollo",
    description: "Fideos instantáneos con clásico sabor a pollo. El favorito de todos.",
    price: 180,
    discount: 0,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/fideos_pollo-q9E1GQdQqbXVB8wiaG6xt5ucjWRKZN.webp",
    category: "alimentos",
    location: "Camagüey",
    publishDate: "2023-05-17",
    contactType: "whatsapp",
    contactNumber: "+58850138",
    sellerName: "tuMercao",
    sellerAvatar: "/placeholder.svg",
    sellerMemberSince: "2022",
  },
  {
    id: "8",
    name: "Salchichas",
    description: "Salchichas de alta calidad. Ideales para desayunos, almuerzos o cenas rápidas.",
    price: 380,
    discount: 0,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/salchichas-VK7D4emD8nFIhOIaDS19RIgXHa1Wuu.webp",
    category: "carnes",
    location: "Camagüey",
    publishDate: "2023-05-18",
    contactType: "whatsapp",
    contactNumber: "+58850138",
    sellerName: "tuMercao",
    sellerAvatar: "/placeholder.svg",
    sellerMemberSince: "2022",
  },
  {
    id: "9",
    name: "Huevo (unidad)",
    description: "Huevo fresco de calidad. Precio por unidad.",
    price: 110,
    discount: 0,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Huevo-8tJT9ysbgMTh9lMxKvrQl0msMNxXrG.webp",
    category: "alimentos",
    location: "Camagüey",
    publishDate: "2023-05-19",
    contactType: "whatsapp",
    contactNumber: "+58850138",
    sellerName: "tuMercao",
    sellerAvatar: "/placeholder.svg",
    sellerMemberSince: "2022",
  },
  {
    id: "10",
    name: "Huevo (cartón)",
    description: "Cartón de huevos frescos. Contiene 30 unidades.",
    price: 3200,
    discount: 0,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Huevo-8tJT9ysbgMTh9lMxKvrQl0msMNxXrG.webp",
    category: "alimentos",
    location: "Camagüey",
    publishDate: "2023-05-19",
    contactType: "whatsapp",
    contactNumber: "+58850138",
    sellerName: "tuMercao",
    sellerAvatar: "/placeholder.svg",
    sellerMemberSince: "2022",
  },
  {
    id: "11",
    name: "Croquetas",
    description: "Deliciosas croquetas listas para freír. Sabor tradicional.",
    price: 200,
    discount: 0,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/croquetas-uCn1T7Li40u5jOinIh5TVqifHnLVGQ.webp",
    category: "alimentos",
    location: "Camagüey",
    publishDate: "2023-05-20",
    contactType: "whatsapp",
    contactNumber: "+58850138",
    sellerName: "tuMercao",
    sellerAvatar: "/placeholder.svg",
    sellerMemberSince: "2022",
  },
]
